### ISSUE TITLE
Rake does not work.

### ISSUE THREAD

**Issue by yosei** [fairfaxmedia/bitbucket2#2]
I tried to run rake to get a token(`rake oauth`). However, I got the following error.

```
$ rake -T
rake aborted!
LoadError: cannot load such file -- rspec/core/rake_task
/vagrant/bitbucket2/Rakefile:2:in `<top (required)>'
```

**Comment by yosei** [comment]
Sorry, I should paste this error, too.

```
$ bundle 
The path `/vagrant/oauth2_rake` does not exist.
```

**Comment by simonhildebrandt** [comment]
Hi Yosei - sorry about the confusion but the `rake oauth` tools are only available to our team here at Fairfax. Collecting OAuth tokens is very application-specific, so I've left it to gem users to build that part themselves - but it's very easy using gems like [oauth2](https://github.com/intridea/oauth2). 

Thanks for the feedback - let me know if you have any other thoughts or ideas.

**Comment by yosei** [comment]
I see. Thank you for the reply!
